name: SGD Test

on:
  push:
    branches:
      - main

permissions:
  actions: read
  contents: read

jobs:
  test-sgd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Check Last successful run
        env:
          GH_TOKEN: ${{github.token}}
        run: |
          echo "=============================="
          echo "CURRENT WORKFLOW"
          echo "================================"

          echo "CURRENT SHA:"
          echo "${{github.sha}}"

          echo ""
          echo "CURRENT EVENT BEFORE:"
          echo "${{github.event.before}}"

          echo ""
          echo "=============================="
          echo "LAST SUCCESSFUL SGD RUN"
          echo "==============================="

          gh run list --workflow=sgd-test.yml --status=success --limit=1 --json databaseId,headSha,status,conclusion,createdAt --jq '.[]'
            
          echo ""
          echo "=============================="
          echo "LAST SUCCESSFUL HEAD SHA"
          echo "==============================="

          LAST_SUCCESSFUL_SHA=$(gh run list --workflow=sgd-test.yml --status=success --limit=1 --json headSha --jq '.[].headSha')

          echo "LAST_SUCCESSFUL_SHA=$LAST_SUCCESSFUL_SHA"

          echo ""
          echo "=============================="
          echo "COMPARISON"
          echo "==============================="

          echo "github.event.before = ${{github.event.before}}"
          echo "latest successful = $LAST_SUCCESSFUL_SHA"
          echo "github.sha = ${{github.sha}}"

      - name: Inspect Successful run
        env:
          GH_TOKEN: ${{github.token}}
        run: |
          echo "ALL RECENT SUCCESSFUL RUNS"
          gh run list --workflow=sgd-test.yml --status=success --limit=10 --json databaseId,headSha,status,conclusion,createdAt --jq '.[]'

      - name: Verify Git History
        run: |
          echo "=============================="
          echo "GIT OBJECT CHECK"
          echo "==============================="

          echo "CURRENT HEAD:"
          git rev-parse HEAD

          echo ""
          echo "COMMIT BEFORE PUSH"
          echo "${{github.event.before}}"

          echo ""
          echo "Current commit:"
          echo "${{github.sha}}"

          echo ""
          echo "Does BEFORE Commit exist?"
          git cat-file -t "${{github.event.before}}"

          echo ""
          echo "Does CURRENT Commit exist?"
          git cat-file -t "${{github.sha}}"

          echo ""
          echo "RECENT HISTORY:"
          git log --oneline --decorate --all -10
      - name: Show git information
        run: |
          echo "=============================="
          echo "CURRENT COMMIT"
          echo "=============================="
          echo "github.sha= ${{github.sha}}"

          echo ""
          echo "=============================="
          echo "BEFORE COMMIT"
          echo "=============================="
          echo "github.event.before= ${{github.event.before}}"

          echo ""
          echo "=============================="
          echo "GIT LOG"
          echo "==============================="
          git log --oneline --all --decorate -10

          echo ""
          echo "=============================="
          echo "GIT BRANCHES"
          echo "==============================="
          git branch -a

      - name: Install Salesforce CLI
        run: |
          npm install --global @salesforce/cli

      - name: Install SGD
        run: |
          echo 'y' | sf plugins install sfdx-git-delta

      - name: Show SGD version
        run: |
          sf plugins

      - name: Compare SGD Baselines
        env:
          GH_TOKEN: ${{github.token}}
        run: |
          echo "=============================="
          echo "GET LAST SUCCESSFUL SHA"
          echo "=============================="

          LAST_SUCCESSFUL_SHA=$(gh run list --workflow=sgd-test.yml --status=success --limit=1 --json headSha --jq '.[].headSha')

          echo "Event Before = ${{github.event.before}}"
          echo "LAST_SUCCESSFUL= $LAST_SUCCESSFUL_SHA"
          echo "Current = ${{github.sha}}"

          echo ""
          echo "=============================="
          echo "DELTA A Event Before -> Current"
          echo "=============================="

          mkdir -p delta-before
          git diff "${{github.event.before}}" "${{github.sha}}" --name-status

          sf sgd source delta --from "${{github.event.before}}" --to "${{github.sha}}" --output-dir delta-before

          echo ""
          echo "DELTA A PACKAGE.XML"
          cat delta-before/package/package.xml


          echo ""
          echo "=============================="
          echo "DELTA B Last Successful -> Current"
          echo "=============================="

          mkdir -p delta-success
          git diff "$LAST_SUCCESSFUL_SHA" "${{github.sha}}" --name-status

          sf sgd source delta --from "$LAST_SUCCESSFUL_SHA" --to "${{github.sha}}" --output-dir delta-success

          echo ""
          echo "DELTA B PACKAGE.XML"
          cat delta-success/package/package.xml

      - name: Create Delta
        run: |
          mkdir -p delta

          echo "=============================="
          echo "SGD input"
          echo "=============================="
          echo "FROM= ${{github.event.before}}"
          echo "TO= ${{github.sha}}"

          echo ""
          echo "============================="
          echo "GIT DIFF"
          echo "============================="
          git diff "${{github.event.before}}" "${{github.sha}}" --name-status

          echo ""
          echo "=============================="
          echo "SGD RUN"
          echo "=============================="

          sf sgd source delta --from "${{github.event.before}}" --to "${{github.sha}}" --output-dir delta

      - name: Show generated package.xml
        run: |
          echo "=============================="
          echo "GENERATED PACKAGE.XML"
          echo "=============================="

          cat delta/package/package.xml

      - name: Intentional CI Failure
        run: |
          echo "Testing failed CI protection"
